# Generated by Django 5.2.7 on 2025-10-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='app_layer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
