# Generated by Django 5.2.7 on 2025-11-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmon', '0002_packet_app_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='payload_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
